spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이징을 1부터 시작하겠다 ( 0 이 아니라 1부터) -- 웹을 통해 요청이 들어왔을때  값을 -1 해서 변환해줌.
        default-page-size: 5
  datasource:
    url: jdbc:h2:mem:paulblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
      active: local
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never  # data.sql 파일 만들어서 해당 파일 내 쿼리 시작할 때 날릴래 말래 지정하는 애임

paul:
  jwt-key: "4vmwG/UGFNTjJI8NFoFKygNMaj5wiKLlHPHVoQrzfR0"